name: ${project.name}
author: Blockcade
version: ${project.version}
api-version: 1.13
main: net.blockcade.HUB.Main
commands:
  debug:
    description: Testing command, remove
  fly:
    description: Toggle flight for players.
    aliases: [togglefly, flight, stuck, imstuck, haxon, hax]
  queue:
    description: Queue for specific gamemode
    aliases:
      - joinqueue
      - search
      - play
  spawn:
    description: Teleport to the spawn
    aliases:
      - home
      - respawn